### PR TITLE
Fix for using ember-leaflet-layer-control on ember-leaflet 3.0.2 (and 3.0.3) which uses ember-composibility-tools

### PR DESCRIPTION
**Pull request by ashleysommer**
Fix for using ember-leaflet-layer-control on ember-leaflet 3.0.2 which uses ember-composibility-tools
Fixes https://github.com/canufeel/ember-leaflet-layer-control/issues/2
Tested on a minimal ember-cli project, with just ember-leaflet and ember-leaflet-layer-control installed.

### CODE REVIEW

**Comment by ashleysommer** [comment]
Upped the version of ember-composibility-tools to version 0.0.3, which fixes a bug, and also upped  ember-leaflet to v3.0.3 (because it also had an update to ember-composibility-tools v 0.0.3)

**Comment by jpalach** [comment]
@ashleysommer you have deleted ember-cli-htmlbars from dependencies in package.json, because of that ember doesn't start. There is a message:

> Addon templates were detected, but there are no template compilers registered for `ember-leaflet-layer-control`. Please make sure your template precompiler (commonly `ember-cli-htmlbars`) is listed in `dependencies` (NOT `devDependencies`) in `ember-leaflet-layer-control`'s `package.json`.

If you restore this line, everything works well (ember-leaflet 3.0.5).

**Comment by ashleysommer** [comment]
Thankyou @jpalach for the heads up.
I am not seeing the problem you describe, ember-cli is working fine for me with `ember-cli-htmlbars` listed in `devDependencies` and not `dependencies`. I'm guessing it is due you using a different version of ember-cli or ember than I am.

It is an easy fix, so I have added `ember-cli-htmlbars` back into the `dependencies` list in this branch. I hope this fixes it for you.

Still hoping @canufeel will pull this into the master codebase.

**Comment by canufeel** [comment]
Hey @ashleysommer i am actually going to though i am lacking time currently and also i do believe that someone should review the changes. If no one else would appear and volunteer i would try to do that myself over the weekend. Thanks for your work and efforts!

@jpalach Can you confirm that everything works for you with the latest changes from the PR?

**Comment by jpalach** [comment]
@canufeel @ashleysommer everything works great for me on ember-cli: 2.9.1, node: 6.9.1 ember-leaflet: 3.0.5, thank you

**Comment by bugduino** [comment]
Any news on this?

**Comment by ashleysommer** [comment]
@bugduino 
It doesn't look like there is much interest from the project owner to merge my three pull-requests.
If you want specifically the functionality from this pull request, you can maybe use the feature-branch of my fork of this repo, here: https://github.com/ashleysommer/ember-leaflet-layer-control/tree/fix_leaflet_302

**Comment by canufeel** [comment]
@ashleysommer Sorry my bad. was pretty busy recently

**Pull request merged**
